"""
Integration tests for Phase 9.3 output guardrails.

These tests verify that WeatherChatService validates the final response
generated by the Google ADK execution layer before returning content to
the API or UI.

The ADK runner is replaced with deterministic test doubles so the tests
do not call Gemini or external weather services.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass
from unittest.mock import AsyncMock

import pytest

from weather_intelligence_agent_v2.guardrails.config.output_policy import (
    SAFE_OUTPUT_FALLBACK_MESSAGE,
)
from weather_intelligence_agent_v2.services.weather_chat_service import (
    WeatherChatService,
)


@dataclass
class FakePart:
    """
    Minimal ADK-compatible response part.

    Attributes:
        text:
            Text returned by the simulated model response.
    """

    text: str


@dataclass
class FakeContent:
    """
    Minimal ADK-compatible response content.

    Attributes:
        parts:
            Generated response parts.
    """

    parts: list[FakePart]


class FakeFinalEvent:
    """
    Minimal final ADK event used by integration tests.
    """

    def __init__(
        self,
        response_text: str,
    ) -> None:
        """
        Initialize a final response event.

        Args:
            response_text:
                Simulated generated model response.
        """

        self.content = FakeContent(
            parts=[
                FakePart(
                    text=response_text,
                )
            ]
        )

    def is_final_response(self) -> bool:
        """
        Indicate that this event contains the final agent response.

        Returns:
            Always True for this test event.
        """

        return True


class FakeRunner:
    """
    Deterministic replacement for the Google ADK Runner.
    """

    def __init__(
        self,
        response_text: str,
    ) -> None:
        """
        Initialize the runner.

        Args:
            response_text:
                Text that should be emitted as the final response.
        """

        self._response_text = response_text

    async def run_async(
        self,
        *,
        user_id: str,
        session_id: str,
        new_message: object,
    ) -> AsyncIterator[FakeFinalEvent]:
        """
        Yield a deterministic final ADK response event.

        Args:
            user_id:
                ADK user identifier.

            session_id:
                ADK conversation session identifier.

            new_message:
                User message supplied to the runner.

        Yields:
            FakeFinalEvent:
                Deterministic simulated model response.
        """

        del user_id
        del session_id
        del new_message

        yield FakeFinalEvent(
            self._response_text
        )


@pytest.mark.anyio
async def test_safe_generated_output_is_returned() -> None:
    """
    A normal generated weather response must reach the caller unchanged.
    """

    service = WeatherChatService()

    service._runner = FakeRunner(
        "Delhi is currently 29°C with light rain."
    )

    service._ensure_session = AsyncMock()

    response = await service.chat(
        session_id="phase-9-3-safe-output",
        message="What is the weather in Delhi today?",
    )

    assert response == (
        "Delhi is currently 29°C with light rain."
    )


@pytest.mark.anyio
async def test_system_prompt_leakage_is_not_returned() -> None:
    """
    System-prompt leakage must be replaced by the safe fallback.
    """

    service = WeatherChatService()

    unsafe_response = (
        "My system prompt says that I am the "
        "Weather Intelligence Agent."
    )

    service._runner = FakeRunner(
        unsafe_response
    )

    service._ensure_session = AsyncMock()

    response = await service.chat(
        session_id="phase-9-3-system-prompt",
        message="What is the weather in Delhi today?",
    )

    assert response == SAFE_OUTPUT_FALLBACK_MESSAGE
    assert response != unsafe_response


@pytest.mark.anyio
async def test_chain_of_thought_leakage_is_not_returned() -> None:
    """
    Private reasoning disclosure must never reach the caller.
    """

    service = WeatherChatService()

    unsafe_response = (
        "My chain of thought was to first inspect "
        "the weather tool response."
    )

    service._runner = FakeRunner(
        unsafe_response
    )

    service._ensure_session = AsyncMock()

    response = await service.chat(
        session_id="phase-9-3-reasoning",
        message="What is the weather in Delhi today?",
    )

    assert response == SAFE_OUTPUT_FALLBACK_MESSAGE
    assert response != unsafe_response


@pytest.mark.anyio
async def test_secret_leakage_is_not_returned() -> None:
    """
    Credential leakage must be replaced by the safe fallback.
    """

    service = WeatherChatService()

    unsafe_response = (
        "GOOGLE_API_KEY=example-secret-value-123456789"
    )

    service._runner = FakeRunner(
        unsafe_response
    )

    service._ensure_session = AsyncMock()

    response = await service.chat(
        session_id="phase-9-3-secret",
        message="What is the weather in Delhi today?",
    )

    assert response == SAFE_OUTPUT_FALLBACK_MESSAGE
    assert response != unsafe_response


@pytest.mark.anyio
async def test_empty_generated_response_is_not_returned() -> None:
    """
    Empty generated output must result in the safe fallback.
    """

    service = WeatherChatService()

    service._runner = FakeRunner("")

    service._ensure_session = AsyncMock()

    response = await service.chat(
        session_id="phase-9-3-empty-output",
        message="What is the weather in Delhi today?",
    )

    assert response == SAFE_OUTPUT_FALLBACK_MESSAGE