apiVersion: v1
kind: ConfigMap

metadata:
  name: weather-intelligence-agent-config

data:
  APP_ENV: "local-kubernetes"
  LOG_LEVEL: "INFO"
  PORT: "8080"

  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector.monitoring:4318/v1/traces"