"""
OpenTelemetry tracing configuration.

This module provides the central tracing configuration for the Weather
Intelligence Agent.

The module intentionally contains only OpenTelemetry SDK bootstrap logic.
Framework-specific instrumentation for FastAPI, Google ADK, Gemini, tools,
and external weather APIs is added separately in later observability phases.
"""

from __future__ import annotations

import logging
import os

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import (
    OTLPSpanExporter,
)
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

LOGGER = logging.getLogger(__name__)

SERVICE_NAME = "weather-intelligence-agent"
SERVICE_VERSION = "1.0.0"

_tracing_configured = False


def configure_tracing() -> None:
    """
    Configure the global OpenTelemetry tracer provider.

    The tracer provider identifies telemetry generated by the Weather
    Intelligence Agent using standard OpenTelemetry resource attributes.

    When ``OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`` is configured, spans are
    exported asynchronously using OTLP over HTTP/Protobuf.

    When no OTLP endpoint is configured, the OpenTelemetry SDK is still
    initialized but no external exporter is registered. This allows local
    development and testing before the OpenTelemetry Collector is deployed.

    The function is idempotent. Repeated calls do not configure tracing
    multiple times.
    """

    global _tracing_configured

    if _tracing_configured:
        return

    resource = Resource.create(
        {
            "service.name": SERVICE_NAME,
            "service.version": SERVICE_VERSION,
            "deployment.environment": os.getenv(
                "APP_ENV",
                "local",
            ),
        }
    )

    tracer_provider = TracerProvider(
        resource=resource,
    )

    otlp_endpoint = os.getenv(
        "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"
    )

    if otlp_endpoint:
        span_exporter = OTLPSpanExporter(
            endpoint=otlp_endpoint,
        )

        span_processor = BatchSpanProcessor(
            span_exporter,
        )

        tracer_provider.add_span_processor(
            span_processor,
        )

        LOGGER.info(
            "OpenTelemetry OTLP trace exporter configured."
        )
    else:
        LOGGER.info(
            "OpenTelemetry initialized without OTLP exporter. "
            "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT is not configured."
        )

    trace.set_tracer_provider(
        tracer_provider
    )

    _tracing_configured = True


def get_tracer(
    instrumentation_name: str,
) -> trace.Tracer:
    """
    Return an OpenTelemetry tracer.

    Args:
        instrumentation_name:
            Logical module or subsystem that will create spans.

    Returns:
        trace.Tracer:
            Configured OpenTelemetry tracer instance.
    """

    return trace.get_tracer(
        instrumentation_name
    )