"""
Conversational weather agent service.

This service encapsulates Google ADK runtime interaction and
conversation-session management.

The API and UI layers must not interact with the ADK Runner
directly.
"""

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from weather_intelligence_agent_v2.agent import (
    root_agent,
)


class WeatherChatService:
    """
    Application service for conversational weather intelligence.

    The service owns interaction with:

    - Google ADK Runner
    - ADK session management
    - Weather Intelligence root agent

    A single service instance is intended to be application scoped.
    """

    APP_NAME = "weather_intelligence_agent"

    USER_ID = "streamlit_user"

    def __init__(self) -> None:
        """
        Initialize the application-scoped ADK runtime.
        """

        self._session_service = (
            InMemorySessionService()
        )

        self._runner = Runner(
            agent=root_agent,
            app_name=self.APP_NAME,
            session_service=self._session_service,
        )

    async def chat(
        self,
        session_id: str,
        message: str,
    ) -> str:
        """
        Send a user message to the weather agent.

        Args:
            session_id:
                Conversation session identifier.

            message:
                User message.

        Returns:
            Final natural-language response generated by the agent.
        """

        await self._ensure_session(
            session_id
        )

        user_message = types.Content(
            role="user",
            parts=[
                types.Part(
                    text=message
                )
            ],
        )

        final_response = ""

        async for event in self._runner.run_async(
            user_id=self.USER_ID,
            session_id=session_id,
            new_message=user_message,
        ):
            if (
                event.is_final_response()
                and event.content
                and event.content.parts
            ):
                final_response = "".join(
                    part.text or ""
                    for part
                    in event.content.parts
                    if getattr(
                        part,
                        "text",
                        None,
                    )
                )

        if not final_response:
            return (
                "I was unable to generate a weather "
                "response. Please try again."
            )

        return final_response

    async def _ensure_session(
        self,
        session_id: str,
    ) -> None:
        """
        Ensure an ADK conversation session exists.

        Args:
            session_id:
                Conversation session identifier.
        """

        existing_session = (
            await self._session_service.get_session(
                app_name=self.APP_NAME,
                user_id=self.USER_ID,
                session_id=session_id,
            )
        )

        if existing_session is not None:
            return

        await self._session_service.create_session(
            app_name=self.APP_NAME,
            user_id=self.USER_ID,
            session_id=session_id,
        )