"""
Google ADK tool-execution guardrail callback.

This module integrates the deterministic Phase 9.4 ToolGuardrail with
Google ADK's before_tool_callback lifecycle hook.

The callback executes after the model requests a tool but before the
actual Python tool function executes.

Returning None allows normal tool execution.

Returning a dictionary prevents the requested tool from executing and
supplies a deterministic blocked result back to the ADK orchestration
layer.
"""

from __future__ import annotations

from typing import Any

from google.adk.tools.base_tool import BaseTool
from google.adk.tools.tool_context import ToolContext

from weather_intelligence_agent_v2.guardrails.tool_guardrail import (
    ToolGuardrail,
)


_TOOL_GUARDRAIL = ToolGuardrail()


def weather_before_tool_callback(
    tool: BaseTool,
    args: dict[str, Any],
    tool_context: ToolContext,
) -> dict[str, Any] | None:
    """
    Validate an ADK tool request before execution.

    Args:
        tool:
            Google ADK tool selected by the model.

        args:
            Arguments generated by the model for the selected tool.

        tool_context:
            Google ADK execution context associated with the tool call.

    Returns:
        None:
            When the tool request is authorized. ADK continues with
            normal tool execution.

        dict[str, Any]:
            When validation fails. Returning a dictionary instructs ADK
            to skip the actual tool execution and use the returned value
            as the tool result.
    """

    del tool_context

    tool_name = getattr(
        tool,
        "name",
        "",
    )

    validation = _TOOL_GUARDRAIL.validate(
        tool_name=tool_name,
        arguments=args,
    )

    if validation.is_valid:
        return None

    return {
        "status": "blocked",
        "error_code": validation.error_code,
        "message": (
            "The requested weather tool operation was blocked "
            "by the tool security policy."
        ),
    }