"""
Enterprise output guardrail orchestration.

The OutputGuardrail validates generated AI responses before they are
returned through the application boundary.

Phase 9.3 deliberately uses deterministic validation so that security
decisions remain predictable, testable, inexpensive, and auditable.
"""

from __future__ import annotations

from weather_intelligence_agent_v2.guardrails.models import (
    ValidationResult,
)
from weather_intelligence_agent_v2.guardrails.validators.leakage_validator import (
    LeakageValidator,
)
from weather_intelligence_agent_v2.guardrails.validators.output_length_validator import (
    OutputLengthValidator,
)
from weather_intelligence_agent_v2.guardrails.validators.pipeline import (
    ValidationPipeline,
)
from weather_intelligence_agent_v2.guardrails.validators.response_integrity_validator import (
    ResponseIntegrityValidator,
)


class OutputGuardrail:
    """
    Coordinate deterministic validation of generated AI responses.

    Validators execute in fail-fast order:

    1. Response integrity
    2. Output length
    3. Sensitive-information leakage

    The guardrail itself contains no business logic. Each validation
    responsibility remains isolated in a dedicated validator.
    """

    def __init__(
        self,
        *,
        debug: bool = False,
    ) -> None:
        """
        Initialise the output-validation pipeline.

        Args:
            debug:
                Enable validation-pipeline diagnostic output.
        """

        self._pipeline = ValidationPipeline(
            validators=(
                ResponseIntegrityValidator(),
                OutputLengthValidator(),
                LeakageValidator(),
            ),
            debug=debug,
        )

    def validate(
        self,
        response: str,
    ) -> ValidationResult:
        """
        Validate a generated AI response.

        Args:
            response:
                Final textual response generated by the AI orchestration
                layer.

        Returns:
            ValidationResult:
                Final deterministic validation decision.
        """

        return self._pipeline.validate(response)